// CRM Components - Export all
export * from "./types"
export { Toast } from "./Toast"
export { StatCard } from "./StatCard"
export { QuickActionCard } from "./QuickActionCard"
export { DashboardView } from "./DashboardView"
export { PipelineView } from "./PipelineView"
export { OpportunitiesKanbanView } from "./OpportunitiesKanbanView"
export { ArchivedOpportunitiesSection } from "./ArchivedOpportunitiesSection"
export { ClientsView } from "./ClientsView"
export { TasksView } from "./TasksView"
export { SocialCalendarView } from "./SocialCalendarView"
export { ClientDetailDrawer } from "./ClientDetailDrawer"
export { OpportunityDetailDrawer } from "./OpportunityDetailDrawer"
export { TaskDetailDrawer } from "./TaskDetailDrawer"
export { ContentDetailDrawer } from "./ContentDetailDrawer"
export { NotificationBell } from "./NotificationBell"
export { default as LinkedTasksPanel } from "./LinkedTasksPanel"

// Re-export notification context types for convenience
export type { Notification } from "../../context/notification-context"
