// Generated by 434-context 04 Build/build_visual_tokens.py. Do not edit.
//
// Literal values, for consumers that cannot resolve CSS custom properties —
// email clients being the reason this file exists. Outlook renders
// `var(--434-signal)` as no colour at all.
//
// Source: 07 Visual System/source, package 1.0 (2026-09-29).

export const COLOR = {
  /** Light atmospheric field / soft brand surface */
  "color-01": "#CAD9D6",
  /** Primary ink; primary logo; light-mode text; dark-mode background */
  "color-02-black": "#000000",
  /** Deep institutional field / restrained brand accent */
  "color-03": "#49625E",
  /** Pale utility field / light neutral surface */
  "color-04": "#E5EBEB",
  /** Secondary neutral / muted brand tone */
  "color-05": "#A2B7B2",
  /** Reverse logo; dark-mode text; primary light background */
  "white": "#FFFFFF",
  /** Functional state signal only */
  "signal": "#D0271D",
} as const

export const ROLE = {
  /** Primary surface, light mode */
  "background": COLOR["white"],
  /** Primary text, light mode */
  "text": COLOR["color-02-black"],
  /** Logo fill, light mode */
  "logo": COLOR["color-02-black"],
  /** Primary surface, dark mode */
  "background-dark": COLOR["color-02-black"],
  /** Primary text, dark mode */
  "text-dark": COLOR["white"],
  /** Logo fill, dark mode */
  "logo-dark": COLOR["white"],
  /** Functional state only */
  "state": COLOR["signal"],
} as const

export const PROHIBITIONS = [
  "Never introduce a new 434 brand colour by inheritance from an old deck, a website component, or a client or owned-IP palette.",
  "Signal is functional state only. It is not decoration, a campaign colour, or a substitute for the palette.",
  "Colour 01, 04 and 05 are not normal-size text on white. Colour 03 is not normal-size text on black.",
  "Never override a client or owned-IP identity to force work into a 434 colour treatment.",
] as const
