import { Resend } from "resend"

/**
 * Verified sending domain in Resend.
 * All `from` addresses MUST end with this domain or Resend will reject the send.
 * Configured in: https://resend.com/domains
 */
export const RESEND_DOMAIN = "send.434media.com"

/**
 * Default sender for transactional CRM emails (cron alerts, follow-up digests).
 * Override per-call by passing a custom `from` ending in `@send.434media.com`.
 */
export const DEFAULT_FROM = `434media CRM <crm@${RESEND_DOMAIN}>`

/**
 * Default sender for outbound prospecting (lead outreach generated by Claude).
 * Separate inbox so replies route to the BD team rather than CRM ops.
 */
export const OUTREACH_FROM = `434media <hello@${RESEND_DOMAIN}>`

let _client: Resend | null = null

/**
 * Lazy-init the Resend SDK so missing env doesn't crash module load.
 * Throws on first use if RESEND_API_KEY isn't set — fail-loud at the boundary.
 */
export function getResend(): Resend {
  if (_client) return _client
  const key = process.env.RESEND_API_KEY
  if (!key) throw new Error("Missing required env var: RESEND_API_KEY")
  _client = new Resend(key)
  return _client
}

/**
 * Validate a `from` address belongs to our verified domain.
 * Use at the boundary of any code path that accepts a configurable sender.
 */
export function assertVerifiedSender(from: string): void {
  if (!from.includes(`@${RESEND_DOMAIN}`)) {
    throw new Error(
      `Sender "${from}" must use the verified Resend domain @${RESEND_DOMAIN}`,
    )
  }
}
