/**
 * Which stills have a WebP derivative worth serving.
 *
 * Generated by scripts/build-still-webp.mjs — do not hand-edit.
 *
 * Standard 3.0 asks for WebP with a JPEG fallback. For 6 of the 52 crops
 * WebP at quality 82 came out LARGER than the JPEG, so those have no WebP and
 * fall through. Never offer the larger file.
 */
export const STILLS_WITH_WEBP: readonly string[] = [
  "280-earth-compact",
  "280-earth-wide",
  "aim-health-summit-compact",
  "alamo-angels-compact",
  "alamo-angels-wide",
  "ampd-project-compact",
  "ampd-project-wide",
  "amplifier-health-compact",
  "amplifier-health-wide",
  "ashbrook-technologies-compact",
  "ashbrook-technologies-wide",
  "breaking-compact",
  "breaking-wide",
  "checkerspot-compact",
  "checkerspot-wide",
  "gradiant-compact",
  "gradiant-wide",
  "milcityusa-compact",
  "mission-road-soar-compact",
  "mission-road-soar-wide",
  "native-microbials-compact",
  "native-microbials-wide",
  "navier-compact",
  "navier-wide",
  "nucleate-global-summit-compact",
  "nucleate-global-summit-wide",
  "overdrive-compact",
  "overdrive-wide",
  "pathos-compact",
  "pathos-wide",
  "pie-vat-compact",
  "pie-vat-wide",
  "que-es-sdoh-compact",
  "que-es-sdoh-wide",
  "rise-of-a-champion-compact",
  "rise-of-a-champion-wide",
  "techbloc-tech-day-compact",
  "techbloc-tech-day-wide",
  "txmx-boxing-compact",
  "txmx-boxing-wide",
  "ubiqd-compact",
  "ubiqd-wide",
  "univision-70th-compact",
  "univision-70th-wide",
  "velocitytx-demo-day-compact",
  "velocitytx-demo-day-wide",
]
