// GENERATED FILE - DO NOT EDIT BY HAND.
// Written by 434media/434-context: 05 System of Record/scripts/emit_work_records.py
// from seed/portfolio_records.json, which is canonical for these records.
// The master holds the record standard and points here; it no longer holds the records.
// Internal context, proof assets and restrictions are deliberately
// excluded - they are not for public display.

export interface WorkRecord {
  title: string
  model: string
  categories: string | null
  client: string | null
  role: string | null
  founderCredit: string | null
  collaboratorCredit: string | null
  years: string | null
  status: string | null
  publicUrl: string | null
  recordKey: string | null
  rightsDefaults: string | null
  registeredIdentifier: string | null
  video: string | null
  displayException: string | null
  description: string | null
}

export const WORK_RECORDS: WorkRecord[] = [
  {
    title: "Salute to Troops",
    model: "Original IP",
    categories: "Experience, Content",
    client: null,
    role: "Owned and produced by 434 MEDIA",
    founderCredit: "Marcos Resendez — Creator, Executive Producer & Creative Director",
    collaboratorCredit: null,
    years: "2022–present",
    status: "Active",
    publicUrl: null,
    recordKey: "salute-to-troops",
    rightsDefaults: "Creator 434 MEDIA · Copyright notice © 2026 434 MEDIA · Credit line 434 MEDIA · Rights usage terms All rights reserved",
    registeredIdentifier: null,
    video: null,
    displayException: null,
    description: "A live entertainment and storytelling property connecting the military community with culture, workforce, innovation, and commercial partners.",
  },
  {
    title: "TXMX Boxing",
    model: "Original IP",
    categories: "Platform, Content, Experience",
    client: null,
    role: "Owned and produced by 434 MEDIA",
    founderCredit: "Marcos Resendez — Creator, Executive Producer & Director",
    collaboratorCredit: null,
    years: "2025–present",
    status: "Active",
    publicUrl: "https://txmxboxing.com",
    recordKey: "txmx-boxing",
    rightsDefaults: "Creator 434 MEDIA · Copyright notice © 2026 434 MEDIA · Credit line 434 MEDIA · Rights usage terms All rights reserved",
    registeredIdentifier: null,
    video: "TXMX DROP TEASER V2.mp4",
    displayException: null,
    description: "A fight-culture media property spanning original content, live experiences, talent, partnerships, and commerce across Texas and Mexico.",
  },
  {
    title: "Rise of a Champion",
    model: "Original IP",
    categories: "Experience, Content, Digital Infrastructure",
    client: "Co-presented with ICON TALKS",
    role: "A TXMX Boxing production owned and produced by 434 MEDIA",
    founderCredit: "Marcos Resendez — Creator, Executive Producer & Director",
    collaboratorCredit: null,
    years: "2025",
    status: "Completed",
    publicUrl: "https://txmxboxing.com/icon-talks/rise-of-a-champion",
    recordKey: "rise-of-a-champion",
    rightsDefaults: "Creator 434 MEDIA · Copyright notice © 2026 434 MEDIA · Credit line 434 MEDIA · Rights usage terms All rights reserved",
    registeredIdentifier: null,
    video: null,
    displayException: null,
    description: "Co-presented with ICON TALKS, Rise of a Champion is a multimedia program culminating in a live tribute to boxing's legacy and the fighters carrying it forward.",
  },
  {
    title: "AMPD Project",
    model: "Original IP",
    categories: "Platform, Digital Infrastructure",
    client: null,
    role: "Owned by 434 MEDIA; co-produced by 434 MEDIA and DEVSA",
    founderCredit: "Marcos Resendez — Creator & Executive Producer",
    collaboratorCredit: null,
    years: "2025–present",
    status: "Annual",
    publicUrl: null,
    recordKey: "ampd-project",
    rightsDefaults: "Creator 434 MEDIA · Copyright notice © 2026 434 MEDIA · Credit line 434 MEDIA · Rights usage terms All rights reserved",
    registeredIdentifier: null,
    video: "ampd.mp4",
    displayException: null,
    description: "An annual eight-week workforce-development program owned by 434 MEDIA and co-produced with DEVSA. Each cohort of emerging technical, web, creative, and production talent completes defined projects that build portfolios and employment pathways.",
  },
  {
    title: "MilCityUSA",
    model: "Original IP",
    categories: "Content",
    client: null,
    role: "Owned and produced by 434 MEDIA",
    founderCredit: "Marcos Resendez — Creator & Executive Producer",
    collaboratorCredit: null,
    years: "2022–present",
    status: "Active",
    publicUrl: null,
    recordKey: "milcityusa",
    rightsDefaults: "Creator 434 MEDIA · Copyright notice © 2026 434 MEDIA · Credit line 434 MEDIA · Rights usage terms All rights reserved",
    registeredIdentifier: null,
    video: null,
    displayException: null,
    description: "An always-on military and defense-community media property that complements Salute to Troops.",
  },
  {
    title: "VemosVamos",
    model: "Original IP",
    categories: "Content, Experience",
    client: null,
    role: "Owned and produced by 434 MEDIA",
    founderCredit: "Marcos Resendez — Creator, Executive Producer & Creative Director",
    collaboratorCredit: null,
    years: "2024–present",
    status: "Selectively activated",
    publicUrl: null,
    recordKey: "vemosvamos",
    rightsDefaults: "Creator 434 MEDIA · Copyright notice © 2026 434 MEDIA · Credit line 434 MEDIA · Rights usage terms All rights reserved",
    registeredIdentifier: null,
    video: null,
    displayException: null,
    description: "A cross-cultural media property rooted in Hispanic culture, media, entertainment, and community connection.",
  },
  {
    title: "OVERDRIVE",
    model: "Original IP",
    categories: "Content",
    client: null,
    role: "Owned, commissioned, and produced by 434 MEDIA",
    founderCredit: "Marcos Resendez — Executive Producer",
    collaboratorCredit: "A.J. Garces — Creator, Writer, Director, Editor, Visual Effects & Post-Production",
    years: "2025",
    status: "Completed",
    publicUrl: null,
    recordKey: "overdrive",
    rightsDefaults: "Creator 434 MEDIA · Copyright notice © 2026 434 MEDIA · Credit line 434 MEDIA · Rights usage terms All rights reserved",
    registeredIdentifier: null,
    video: null,
    displayException: null,
    description: "A 2:58 original short film commissioned by 434 MEDIA as a demonstration of its Human Plus production philosophy.",
  },
  {
    title: "¿Qué es SDOH?",
    model: "Platforms for Brands",
    categories: "Platform, Content, Experience, Digital Infrastructure",
    client: "VelocityTX, funded through Methodist Healthcare Ministries",
    role: "Brand and platform development; full program production",
    founderCredit: "Marcos Resendez — Executive Producer, Program Lead & Moderator",
    collaboratorCredit: null,
    years: "2024–2025",
    status: "Completed",
    publicUrl: "https://434media.com/en/sdoh",
    recordKey: "que-es-sdoh",
    rightsDefaults: "Creator 434 MEDIA · Copyright notice © 2026 434 MEDIA · Credit line 434 MEDIA · Rights usage terms All rights reserved",
    registeredIdentifier: null,
    video: "SDOH ACCELERATOR PROGRAM RECAP_2025.mp4",
    displayException: null,
    description: "434 developed the ¿Qué es SDOH? bilingual brand and public-facing platform and produced the full Community Health Accelerator experience. Work included program infrastructure, content strategy and production, panel production and moderation, speaker and mentor curation, a hero film, Univision broadcast segments, demo day, digital infrastructure, communications, and impact-report development.",
  },
  {
    title: "AIM Health R&D Summit",
    model: "Platforms for Brands",
    categories: "Platform, Experience, Digital Infrastructure",
    client: "VelocityTX",
    role: "Brand and platform development; full conference production and digital infrastructure",
    founderCredit: "Marcos Resendez — Creator, Executive Producer, Conference Producer & Project Lead",
    collaboratorCredit: null,
    years: "2023–2026",
    status: "Completed",
    publicUrl: "https://www.brdgsatx.com/",
    recordKey: "aim-health-summit",
    rightsDefaults: "Creator 434 MEDIA · Copyright notice © 2026 434 MEDIA · Credit line 434 MEDIA · Rights usage terms All rights reserved",
    registeredIdentifier: null,
    video: null,
    displayException: null,
    description: "434 created the AIM Health R&D Summit brand and operating platform and produced the conference over four years. The engagement included brand development, conference production, project management, digital infrastructure, vendor coordination, operating systems, impact reporting, and strategic marketing guidance.",
  },
  {
    title: "Alamo Angels",
    model: "Platforms for Brands",
    categories: "Platform, Content, Experience, Digital Infrastructure",
    client: "Alamo Angels",
    role: "Ongoing strategic marketing adviser, platform-development partner, and production partner",
    founderCredit: "Marcos Resendez — Strategic Marketing Adviser & Executive Producer",
    collaboratorCredit: null,
    years: "2023–present",
    status: "Ongoing client engagement",
    publicUrl: null,
    recordKey: "alamo-angels",
    rightsDefaults: "Creator 434 MEDIA · Copyright notice © 2026 434 MEDIA · Credit line 434 MEDIA · Rights usage terms All rights reserved",
    registeredIdentifier: null,
    video: null,
    displayException: null,
    description: "Since 2023, 434 has advised Alamo Angels on its marketing strategy and translated that strategy into an interconnected system of events, content, messaging, and digital infrastructure, including the organization’s member portal.",
  },
  {
    title: "TechBloc Tech Day",
    model: "Platforms for Brands",
    categories: "Platform, Content, Experience, Digital Infrastructure",
    client: "TechBloc",
    role: "Event architecture, visual identity, platform development, and lead production",
    founderCredit: "Marcos Resendez — Executive Producer, Creative Director & Event Director",
    collaboratorCredit: null,
    years: "2025–2026",
    status: "Completed",
    publicUrl: "https://www.sanantoniotechday.com/",
    recordKey: "techbloc-tech-day",
    rightsDefaults: "Creator 434 MEDIA · Copyright notice © 2026 434 MEDIA · Credit line 434 MEDIA · Rights usage terms All rights reserved",
    registeredIdentifier: null,
    video: null,
    displayException: null,
    description: "434 served as Tech Day’s lead production and platform partner during an organizational transition, translating the incoming CEO’s vision into an updated event identity, operating model, programming, content, and audience experience.",
  },
  {
    title: "Mission Road Ministries — Fundraising",
    model: "Productions for Brands",
    categories: "Content",
    client: "Mission Road Ministries",
    role: "Commissioned fundraising-film production",
    founderCredit: "Marcos Resendez — Co-Executive Producer, Co-Producer & Co-Director",
    collaboratorCredit: null,
    years: "2025–2026",
    status: "Completed",
    publicUrl: "https://missionroadministries.org",
    recordKey: "mission-road-soar",
    rightsDefaults: "Creator 434 MEDIA · Copyright notice © 2026 434 MEDIA · Credit line 434 MEDIA · Rights usage terms All rights reserved",
    registeredIdentifier: null,
    video: null,
    displayException: null,
    description: "434 produced primary fundraising films for Mission Road Ministries featuring its SOAR & Symbol of Success programs. The films premiered at the organization's Annual Grand Western Shindig and were created for continued fundraising use throughout the year.",
  },
  {
    title: "Univision San Antonio — 70th Anniversary Concert",
    model: "Productions for Brands",
    categories: "Content",
    client: "Univision San Antonio",
    role: "Event and sponsor content production",
    founderCredit: "Marcos Resendez — Co-Executive Producer, Producer & Director",
    collaboratorCredit: null,
    years: "2025",
    status: "Completed",
    publicUrl: null,
    recordKey: "univision-70th",
    rightsDefaults: "Creator 434 MEDIA · Copyright notice © 2026 434 MEDIA · Credit line 434 MEDIA · Rights usage terms All rights reserved",
    registeredIdentifier: null,
    video: "Alejandro Fernández Concert .mov",
    displayException: null,
    description: "434 produced a social event recap for Univision San Antonio and individual video deliverables for three participating advertisers — Jeff Davis Law Firm, Cavender Boot City, and Cavender Toyota — in support of the station’s private 70th-anniversary concert featuring Alex Fernández, presented by Miller Lite.",
  },
  {
    title: "Nucleate Global Summit",
    model: "Productions for Brands",
    categories: "Experience, Content",
    client: "Nucleate",
    role: "Production partner responsible for vendor sourcing, on-site production support, content capture, and co-production and post-production of the final media deliverable",
    founderCredit: "Marcos Resendez — Co-Producer & Technical Director",
    collaboratorCredit: null,
    years: "2026",
    status: "Completed",
    publicUrl: null,
    recordKey: "nucleate-global-summit",
    rightsDefaults: "Creator 434 MEDIA · Copyright notice © 2026 434 MEDIA · Credit line 434 MEDIA · Rights usage terms All rights reserved",
    registeredIdentifier: null,
    video: null,
    displayException: null,
    description: "434 supported the Nucleate Global Summit through production-vendor sourcing, on-site logistical and technical support, content capture, and media co-production.",
  },
  {
    title: "VelocityTX — SDOH Community Health Accelerator Demo Day",
    model: "Productions for Brands",
    categories: "Experience, Content",
    client: "VelocityTX, funded through Methodist Healthcare Ministries",
    role: "Executive Producer and Technical Director",
    founderCredit: "Marcos Resendez — Executive Producer & Technical Director",
    collaboratorCredit: null,
    years: "2024",
    status: "Completed",
    publicUrl: null,
    recordKey: "velocitytx-demo-day",
    rightsDefaults: "Creator 434 MEDIA · Copyright notice © 2026 434 MEDIA · Credit line 434 MEDIA · Rights usage terms All rights reserved",
    registeredIdentifier: null,
    video: null,
    displayException: null,
    description: "434 produced the SDOH Community Health Accelerator Demo Day, the culminating event of the program's inaugural year. Our work included event and stage design, run-of-show development, show direction, room production, videography, and a complete content package.",
  },
  {
    title: "280 Earth",
    model: "Productions for Brands",
    categories: "Content",
    client: "Builders VC",
    role: "Co-Executive Producer, Producer, Editor",
    founderCredit: null,
    collaboratorCredit: null,
    years: "2025",
    status: "Completed",
    publicUrl: null,
    recordKey: "280-earth",
    rightsDefaults: "Creator 434 MEDIA · Copyright notice © 2025 434 MEDIA · Credit line 434 MEDIA · Rights usage terms All rights reserved",
    registeredIdentifier: null,
    video: null,
    displayException: "tile-4x5-upscale; factor 1.39× from an 864×1080 crop, the widest 4:5 a 1080-tall source gives; beyond the 15% allowance in Display and Design Standard 3.1; founder-approved 2026-09-30; interim until higher-resolution stills are supplied. The 16:9 tile needs no upscale and is met exactly at 1920×1080. Left edge of the 4:5 window in the 1920×1080 frame: 471 px.",
    description: "Spun out of X, Alphabet's moonshot factory, it builds modular direct air capture systems that use waste heat to remove carbon dioxide from the atmosphere. Produced for Builders VC's 2025 annual general meeting, with 434 as co-executive producer, producer and editor.",
  },
  {
    title: "Amplifier Health",
    model: "Productions for Brands",
    categories: "Content",
    client: "Builders VC",
    role: "Co-Executive Producer, Producer, Editor",
    founderCredit: null,
    collaboratorCredit: null,
    years: "2024",
    status: "Completed",
    publicUrl: null,
    recordKey: "amplifier-health",
    rightsDefaults: "Creator 434 MEDIA · Copyright notice © 2024 434 MEDIA · Credit line 434 MEDIA · Rights usage terms All rights reserved",
    registeredIdentifier: null,
    video: null,
    displayException: "tile-4x5-upscale; factor 1.39× from an 864×1080 crop, the widest 4:5 a 1080-tall source gives; beyond the 15% allowance in Display and Design Standard 3.1; founder-approved 2026-09-30; interim until higher-resolution stills are supplied. The 16:9 tile needs no upscale and is met exactly at 1920×1080. Left edge of the 4:5 window in the 1920×1080 frame: 530 px.",
    description: "Developing an acoustic AI model that detects health conditions from the human voice. Produced for Builders VC's 2024 annual general meeting, with 434 as co-executive producer, producer and editor.",
  },
  {
    title: "Ashbrook Technologies",
    model: "Productions for Brands",
    categories: "Content",
    client: "Builders VC",
    role: "Co-Executive Producer, Producer, Editor",
    founderCredit: null,
    collaboratorCredit: null,
    years: "2025",
    status: "Completed",
    publicUrl: null,
    recordKey: "ashbrook-technologies",
    rightsDefaults: "Creator 434 MEDIA · Copyright notice © 2025 434 MEDIA · Credit line 434 MEDIA · Rights usage terms All rights reserved",
    registeredIdentifier: null,
    video: null,
    displayException: "tile-4x5-upscale; factor 1.39× from an 864×1080 crop, the widest 4:5 a 1080-tall source gives; beyond the 15% allowance in Display and Design Standard 3.1; founder-approved 2026-09-30; interim until higher-resolution stills are supplied. The 16:9 tile needs no upscale and is met exactly at 1920×1080. Left edge of the 4:5 window in the 1920×1080 frame: 626 px.",
    description: "Gives farmers, advisors and agents real-time tools to manage crop, livestock and revenue risk. Produced for Builders VC's 2025 annual general meeting, with 434 as co-executive producer, producer and editor.",
  },
  {
    title: "Breaking",
    model: "Productions for Brands",
    categories: "Content",
    client: "Builders VC",
    role: "Co-Executive Producer, Producer, Editor",
    founderCredit: null,
    collaboratorCredit: null,
    years: "2024",
    status: "Completed",
    publicUrl: null,
    recordKey: "breaking",
    rightsDefaults: "Creator 434 MEDIA · Copyright notice © 2024 434 MEDIA · Credit line 434 MEDIA · Rights usage terms All rights reserved",
    registeredIdentifier: null,
    video: null,
    displayException: "tile-4x5-upscale; factor 1.39× from an 864×1080 crop, the widest 4:5 a 1080-tall source gives; beyond the 15% allowance in Display and Design Standard 3.1; founder-approved 2026-09-30; interim until higher-resolution stills are supplied. The 16:9 tile needs no upscale and is met exactly at 1920×1080. Left edge of the 4:5 window in the 1920×1080 frame: 530 px.",
    description: "Developing a biological approach to breaking down plastic waste. Produced for Builders VC's 2024 annual general meeting, with 434 as co-executive producer, producer and editor.",
  },
  {
    title: "Checkerspot",
    model: "Productions for Brands",
    categories: "Content",
    client: "Builders VC",
    role: "Co-Executive Producer, Producer, Editor",
    founderCredit: null,
    collaboratorCredit: null,
    years: "2025",
    status: "Completed",
    publicUrl: null,
    recordKey: "checkerspot",
    rightsDefaults: "Creator 434 MEDIA · Copyright notice © 2025 434 MEDIA · Credit line 434 MEDIA · Rights usage terms All rights reserved",
    registeredIdentifier: null,
    video: null,
    displayException: "tile-4x5-upscale; factor 1.39× from an 864×1080 crop, the widest 4:5 a 1080-tall source gives; beyond the 15% allowance in Display and Design Standard 3.1; founder-approved 2026-09-30; interim until higher-resolution stills are supplied. The 16:9 tile needs no upscale and is met exactly at 1920×1080. Left edge of the 4:5 window in the 1920×1080 frame: 430 px.",
    description: "Uses precision fermentation and microalgae to produce specialty oils, licensing its processes to partners instead of building its own plants. Produced for Builders VC's 2025 annual general meeting, with 434 as co-executive producer, producer and editor.",
  },
  {
    title: "Gradiant",
    model: "Productions for Brands",
    categories: "Content",
    client: "Builders VC",
    role: "Co-Executive Producer, Producer, Editor",
    founderCredit: null,
    collaboratorCredit: null,
    years: "2024",
    status: "Completed",
    publicUrl: null,
    recordKey: "gradiant",
    rightsDefaults: "Creator 434 MEDIA · Copyright notice © 2024 434 MEDIA · Credit line 434 MEDIA · Rights usage terms All rights reserved",
    registeredIdentifier: null,
    video: null,
    displayException: "tile-4x5-upscale; factor 1.39× from an 864×1080 crop, the widest 4:5 a 1080-tall source gives; beyond the 15% allowance in Display and Design Standard 3.1; founder-approved 2026-09-30; interim until higher-resolution stills are supplied. The 16:9 tile needs no upscale and is met exactly at 1920×1080. Left edge of the 4:5 window in the 1920×1080 frame: 471 px.",
    description: "An MIT spinout building water treatment and recycling systems for industrial users. Produced for Builders VC's 2024 annual general meeting, with 434 as co-executive producer, producer and editor.",
  },
  {
    title: "Native Microbials",
    model: "Productions for Brands",
    categories: "Content",
    client: "Builders VC",
    role: "Co-Executive Producer, Producer, Editor",
    founderCredit: null,
    collaboratorCredit: null,
    years: "2024",
    status: "Completed",
    publicUrl: null,
    recordKey: "native-microbials",
    rightsDefaults: "Creator 434 MEDIA · Copyright notice © 2024 434 MEDIA · Credit line 434 MEDIA · Rights usage terms All rights reserved",
    registeredIdentifier: null,
    video: null,
    displayException: "tile-4x5-upscale; factor 1.39× from an 864×1080 crop, the widest 4:5 a 1080-tall source gives; beyond the 15% allowance in Display and Design Standard 3.1; founder-approved 2026-09-30; interim until higher-resolution stills are supplied. The 16:9 tile needs no upscale and is met exactly at 1920×1080. Left edge of the 4:5 window in the 1920×1080 frame: 430 px.",
    description: "Develops species-specific microbial products for animal health. Produced for Builders VC's 2024 annual general meeting, with 434 as co-executive producer, producer and editor.",
  },
  {
    title: "Navier",
    model: "Productions for Brands",
    categories: "Content",
    client: "Builders VC",
    role: "Co-Executive Producer, Producer, Editor",
    founderCredit: null,
    collaboratorCredit: null,
    years: "2024",
    status: "Completed",
    publicUrl: null,
    recordKey: "navier",
    rightsDefaults: "Creator 434 MEDIA · Copyright notice © 2024 434 MEDIA · Credit line 434 MEDIA · Rights usage terms All rights reserved",
    registeredIdentifier: null,
    video: null,
    displayException: "tile-4x5-upscale; factor 1.39× from an 864×1080 crop, the widest 4:5 a 1080-tall source gives; beyond the 15% allowance in Display and Design Standard 3.1; founder-approved 2026-09-30; interim until higher-resolution stills are supplied. The 16:9 tile needs no upscale and is met exactly at 1920×1080. Left edge of the 4:5 window in the 1920×1080 frame: 585 px.",
    description: "Builds electric hydrofoil vessels and waterborne transit services for coastal cities. Produced for Builders VC's 2024 annual general meeting, with 434 as co-executive producer, producer and editor.",
  },
  {
    title: "Pathos",
    model: "Productions for Brands",
    categories: "Content",
    client: "Builders VC",
    role: "Co-Executive Producer, Producer, Editor",
    founderCredit: null,
    collaboratorCredit: null,
    years: "2025",
    status: "Completed",
    publicUrl: null,
    recordKey: "pathos",
    rightsDefaults: "Creator 434 MEDIA · Copyright notice © 2025 434 MEDIA · Credit line 434 MEDIA · Rights usage terms All rights reserved",
    registeredIdentifier: null,
    video: null,
    displayException: "tile-4x5-upscale; factor 1.39× from an 864×1080 crop, the widest 4:5 a 1080-tall source gives; beyond the 15% allowance in Display and Design Standard 3.1; founder-approved 2026-09-30; interim until higher-resolution stills are supplied. The 16:9 tile needs no upscale and is met exactly at 1920×1080. Left edge of the 4:5 window in the 1920×1080 frame: 626 px.",
    description: "A clinical-stage oncology company using AI and real-world clinical data to guide drug development and patient selection. Produced for Builders VC's 2025 annual general meeting, with 434 as co-executive producer, producer and editor.",
  },
  {
    title: "Pie VAT",
    model: "Productions for Brands",
    categories: "Content",
    client: "Builders VC",
    role: "Co-Executive Producer, Producer, Editor",
    founderCredit: null,
    collaboratorCredit: null,
    years: "2024",
    status: "Completed",
    publicUrl: null,
    recordKey: "pie-vat",
    rightsDefaults: "Creator 434 MEDIA · Copyright notice © 2024 434 MEDIA · Credit line 434 MEDIA · Rights usage terms All rights reserved",
    registeredIdentifier: null,
    video: null,
    displayException: "tile-4x5-upscale; factor 1.39× from an 864×1080 crop, the widest 4:5 a 1080-tall source gives; beyond the 15% allowance in Display and Design Standard 3.1; founder-approved 2026-09-30; interim until higher-resolution stills are supplied. The 16:9 tile needs no upscale and is met exactly at 1920×1080. Left edge of the 4:5 window in the 1920×1080 frame: 297 px.",
    description: "Digitizing the VAT refund process for international travelers. Produced for Builders VC's 2024 annual general meeting, with 434 as co-executive producer, producer and editor.",
  },
  {
    title: "UbiQD",
    model: "Productions for Brands",
    categories: "Content",
    client: "Builders VC",
    role: "Co-Executive Producer, Producer, Editor",
    founderCredit: null,
    collaboratorCredit: null,
    years: "2025",
    status: "Completed",
    publicUrl: null,
    recordKey: "ubiqd",
    rightsDefaults: "Creator 434 MEDIA · Copyright notice © 2025 434 MEDIA · Credit line 434 MEDIA · Rights usage terms All rights reserved",
    registeredIdentifier: null,
    video: null,
    displayException: "tile-4x5-upscale; factor 1.39× from an 864×1080 crop, the widest 4:5 a 1080-tall source gives; beyond the 15% allowance in Display and Design Standard 3.1; founder-approved 2026-09-30; interim until higher-resolution stills are supplied. The 16:9 tile needs no upscale and is met exactly at 1920×1080. Left edge of the 4:5 window in the 1920×1080 frame: 722 px.",
    description: "Manufactures quantum dot materials that improve how greenhouses, solar panels and other systems use light. Produced for Builders VC's 2025 annual general meeting, with 434 as co-executive producer, producer and editor.",
  }
]
