// GENERATED FILE - DO NOT EDIT BY HAND.
// Written by scripts/master_extract.py from the canonical master.
// Master version 2.0.15 (September 17, 2026). Regenerate after any section 4 change.
// Internal context, proof assets and restrictions are deliberately
// excluded - they are not for public display.

export interface WorkRecord {
  title: string
  model: string
  categories: string | null
  client: string | null
  role: string | null
  founderCredit: string | null
  collaboratorCredit: string | null
  years: string | null
  status: string | null
  publicUrl: string | null
  description: string | null
}

export const WORK_RECORDS: WorkRecord[] = [
  {
    title: "Salute to Troops",
    model: "Original IP",
    categories: "Experience, Content",
    client: null,
    role: "Owned and produced by 434 MEDIA",
    founderCredit: "Marcos Resendez — Creator, Executive Producer & Creative Director",
    collaboratorCredit: null,
    years: "2022",
    status: "Active owned property",
    publicUrl: null,
    description: "A live entertainment and storytelling property connecting the military community with culture, workforce, innovation, and commercial partners.",
  },
  {
    title: "TXMX Boxing",
    model: "Original IP",
    categories: "Platform, Content, Experience",
    client: null,
    role: "Owned and produced by 434 MEDIA",
    founderCredit: "Marcos Resendez — Creator, Executive Producer & Director",
    collaboratorCredit: null,
    years: "2025",
    status: "Active",
    publicUrl: "https://txmxboxing.com",
    description: "A fight-culture media property spanning original content, live experiences, talent, partnerships, and commerce across Texas and Mexico.",
  },
  {
    title: "Rise of a Champion",
    model: "Original IP",
    categories: "Experience, Content, Digital Infrastructure",
    client: "Co-presented with Icontalks",
    role: "A TXMX Boxing production owned and produced by 434 MEDIA",
    founderCredit: "Marcos Resendez — Creator, Executive Producer & Director",
    collaboratorCredit: null,
    years: null,
    status: "Completed",
    publicUrl: "https://txmxboxing.com/icon-talks/rise-of-a-champion",
    description: "A TXMX Boxing live production honoring championship fighters and figures connected to San Antonio boxing, supported by original content and a purpose-built digital experience.",
  },
  {
    title: "AMPD Project",
    model: "Original IP",
    categories: "Platform, Digital Infrastructure",
    client: null,
    role: "Owned by 434 MEDIA; co-produced by 434 MEDIA and DEVSA",
    founderCredit: "Marcos Resendez — Creator & Executive Producer",
    collaboratorCredit: null,
    years: null,
    status: "Annual",
    publicUrl: null,
    description: "AMPD Project is an established eight-week workforce-development program now operated as a 434-owned property. After two years as a program, its parent nonprofit entity is being dissolved and the program, history, assets, and public presence are being consolidated under 434 MEDIA. Digital Canvas assets are also being incorporated into the program. AMPD Project will continue annually, using emerging technical, web, creative, and production talent to complete defined projects that build portfolios and employment pathways. A cohort may work within 434’s environment and owned properties or on an underwriter-supported project.",
  },
  {
    title: "MilCityUSA",
    model: "Original IP",
    categories: "Content",
    client: null,
    role: "Owned and produced by 434 MEDIA",
    founderCredit: "Marcos Resendez — Creator & Executive Producer",
    collaboratorCredit: null,
    years: "2022",
    status: "Active",
    publicUrl: null,
    description: "An always-on military and defense-community media property that complements Salute to Troops.",
  },
  {
    title: "VemosVamos",
    model: "Original IP",
    categories: "Content, Experience",
    client: null,
    role: "Owned and produced by 434 MEDIA",
    founderCredit: "Marcos Resendez — Creator, Executive Producer & Creative Director",
    collaboratorCredit: null,
    years: null,
    status: "Selectively activated",
    publicUrl: null,
    description: "A cross-cultural media property rooted in Hispanic culture, media, entertainment, and community connection.",
  },
  {
    title: "OVERDRIVE",
    model: "Original IP",
    categories: "Content",
    client: null,
    role: "Owned, commissioned, and produced by 434 MEDIA",
    founderCredit: "Marcos Resendez — Executive Producer",
    collaboratorCredit: "A.J. Garces — Creator, Writer, Director, Editor, Visual Effects & Post-Production",
    years: "2026",
    status: "Completed",
    publicUrl: null,
    description: "A 2:58 original short film commissioned by 434 MEDIA as a demonstration of its Human Plus production philosophy.",
  },
  {
    title: "¿Qué es SDOH?",
    model: "Platforms for Brands",
    categories: "Platform, Content, Experience, Digital Infrastructure",
    client: "VelocityTX, funded through Methodist Healthcare Ministries",
    role: "Brand and platform development; full program production",
    founderCredit: "Marcos Resendez — Executive Producer, Program Lead & Moderator",
    collaboratorCredit: null,
    years: "2024–2025",
    status: "Completed",
    publicUrl: "https://434media.com/en/sdoh",
    description: "434 developed the ¿Qué es SDOH? bilingual brand and public-facing platform and produced the full Community Health Accelerator experience. Work included program infrastructure, content strategy and production, panel production and moderation, speaker and mentor curation, a hero film, Univision broadcast segments, demo day, digital infrastructure, communications, and impact-report development.",
  },
  {
    title: "AIM Health R&D Summit",
    model: "Platforms for Brands",
    categories: "Platform, Experience, Digital Infrastructure",
    client: "VelocityTX",
    role: "Brand and platform development; full conference production and digital infrastructure",
    founderCredit: "Marcos Resendez — Creator, Executive Producer, Conference Producer & Project Lead",
    collaboratorCredit: null,
    years: "2023–2026",
    status: "Completed and handed off",
    publicUrl: "https://aimsatx.com",
    description: "434 created the AIM Health R&D Summit brand and operating platform and produced the conference over four years. The engagement included brand development, conference production, project management, digital infrastructure, vendor coordination, operating systems, impact reporting, and strategic marketing guidance.",
  },
  {
    title: "Alamo Angels",
    model: "Platforms for Brands",
    categories: "Platform, Content, Experience, Digital Infrastructure",
    client: "Alamo Angels",
    role: "Ongoing strategic marketing adviser, platform-development partner, and production partner",
    founderCredit: "Marcos Resendez — Strategic Marketing Adviser & Executive Producer",
    collaboratorCredit: null,
    years: null,
    status: "Ongoing client engagement",
    publicUrl: null,
    description: "For three years, 434 has advised Alamo Angels on its marketing strategy and translated that strategy into an interconnected system of events, content, messaging, and digital infrastructure, including the organization’s member portal.",
  },
  {
    title: "TechBloc Tech Day",
    model: "Platforms for Brands",
    categories: "Platform, Content, Experience, Digital Infrastructure",
    client: "TechBloc",
    role: "Event architecture, visual identity, platform development, and lead production",
    founderCredit: "Marcos Resendez — Executive Producer, Creative Director & Event Director",
    collaboratorCredit: null,
    years: "November 2025 and April 2026",
    status: "Completed",
    publicUrl: "https://sanantoniotechday.com",
    description: "434 served as Tech Day’s lead production and platform partner during an organizational transition, translating the incoming CEO’s vision into an updated event identity, operating model, programming, content, and audience experience.",
  },
  {
    title: "Mission Road Ministries — Fundraising Film Featuring SOAR",
    model: "Productions for Brands",
    categories: "Content",
    client: "Mission Road Ministries",
    role: "Commissioned fundraising-film production",
    founderCredit: "Marcos Resendez — Co-Executive Producer, Co-Producer & Co-Director",
    collaboratorCredit: null,
    years: null,
    status: "Completed",
    publicUrl: "https://missionroadministries.org",
    description: "434 produced a primary fundraising film for Mission Road Ministries featuring its SOAR program. The film premiered at the organization’s Annual Grand Western Shindig and was created for continued fundraising use throughout the year.",
  },
  {
    title: "Univision San Antonio 70th Anniversary Concert — Event and Sponsor Content",
    model: "Productions for Brands",
    categories: "Content",
    client: "Univision San Antonio",
    role: "Event and sponsor content production",
    founderCredit: "Marcos Resendez — Co-Executive Producer, Producer & Director",
    collaboratorCredit: null,
    years: "2025",
    status: "Completed",
    publicUrl: null,
    description: "434 produced a social event recap for Univision San Antonio and individual video deliverables for three participating advertisers — Jeff Davis Law Firm, Cavender Boot City, and Cavender Toyota — in support of the station’s private 70th-anniversary concert featuring Alex Fernández, presented by Miller Lite.",
  },
  {
    title: "Nucleate Global Summit",
    model: "Productions for Brands",
    categories: "Experience, Content",
    client: "Nucleate",
    role: "Production partner responsible for vendor sourcing, on-site production support, content capture, and co-production and post-production of the final media deliverable",
    founderCredit: "Marcos Resendez — Co-Producer & Technical Director",
    collaboratorCredit: null,
    years: "2026",
    status: "Event-production scope completed",
    publicUrl: null,
    description: "434 supported the Nucleate Global Summit through production-vendor sourcing, on-site logistical and technical support, content capture, and media co-production.",
  },
  {
    title: "VelocityTX — SDOH Community Health Accelerator Demo Day",
    model: "Productions for Brands",
    categories: "Experience, Content",
    client: "VelocityTX, funded through Methodist Healthcare Ministries",
    role: "Executive Producer and Technical Director",
    founderCredit: "Marcos Resendez — Executive Producer & Technical Director",
    collaboratorCredit: null,
    years: "2024",
    status: "Completed",
    publicUrl: null,
    description: "434 produced the SDOH Community Health Accelerator Demo Day, the culminating event of the program's inaugural year. Our work included event and stage design, run-of-show development, show direction, room production, videography, and a complete content package.",
  }
]
