/**
 * Generate `lib/sor/types.generated.ts` from the system-of-record JSON Schemas.
 *
 * The schemas are canonical and live in the private context repository
 * (`434-context/05 System of Record/schemas`), not here. They carry no figures —
 * only field names and structural enums — but they do describe the shape of
 * qualification and rate-card data, which this repository is public and does not
 * hold. So the schemas stay there and only the generated output lands here.
 *
 * That splits the drift question in two, the same way `scripts/check_drift.py`
 * already splits it for the master:
 *
 *   - **Did a schema change without the types being regenerated?** Only
 *     answerable where the schemas are. `sorSchemaHashes` records each schema's
 *     sha256 so the private repo can compare.
 *   - **Was the generated file hand-edited?** Answerable here, with no access to
 *     the schemas, by re-hashing the file's own body. That is what CI checks.
 *
 * Tool: json-schema-to-typescript (bcherny), the standard JSON-Schema-to-
 * TypeScript code generator. Its documented gaps are all 2020-12 keywords these
 * schemas do not use — $anchor, $dynamicRef, $dynamicAnchor, $recursiveRef,
 * $recursiveAnchor, $vocabulary, unevaluatedItems, unevaluatedProperties,
 * prefixItems, dependentSchemas, dependentRequired — which is checked below
 * rather than assumed, so the run fails if a schema later adopts one.
 *
 * Usage: tsx scripts/sor/generate-types.ts [--schemas <dir>] [--check]
 *   --check exits non-zero instead of writing, for CI.
 */
import { createHash } from "node:crypto"
import { readFileSync, writeFileSync, readdirSync, existsSync } from "node:fs"
import { join, resolve, basename } from "node:path"
import { compile } from "json-schema-to-typescript"

const OUT = resolve("lib/sor/types.generated.ts")
const BANNER = "// Generated by scripts/sor/generate-types.ts. Do not edit."

/** Keywords json-schema-to-typescript does not implement. */
const UNSUPPORTED = [
  "$anchor", "$dynamicRef", "$dynamicAnchor", "$recursiveRef", "$recursiveAnchor",
  "$vocabulary", "unevaluatedItems", "unevaluatedProperties", "prefixItems",
  "dependentSchemas", "dependentRequired",
]

function schemaDir(): string {
  const flag = process.argv.indexOf("--schemas")
  if (flag !== -1 && process.argv[flag + 1]) return resolve(process.argv[flag + 1])
  for (const candidate of [
    "docs/context/../../434-context/05 System of Record/schemas",
    "../434-context/05 System of Record/schemas",
  ]) {
    const path = resolve(candidate)
    if (existsSync(path)) return path
  }
  throw new Error(
    "Schemas not found. They live in the private context repository; pass --schemas <dir>."
  )
}

/** sha256 of the file body below the banner, so the banner itself is not self-referential. */
export function bodyHash(source: string): string {
  const body = source.slice(source.indexOf("\n", source.indexOf(BANNER)) + 1)
  return createHash("sha256").update(body).digest("hex").slice(0, 16)
}

async function main() {
  const dir = schemaDir()
  const files = readdirSync(dir).filter((f) => f.endsWith(".schema.json")).sort()
  if (files.length === 0) throw new Error(`No schemas in ${dir}`)

  const hashes: Record<string, string> = {}
  const blocks: string[] = []

  for (const file of files) {
    const raw = readFileSync(join(dir, file), "utf8")
    const used = UNSUPPORTED.filter((k) => raw.includes(`"${k}"`))
    if (used.length) {
      throw new Error(
        `${file} uses ${used.join(", ")}, which json-schema-to-typescript does not implement. ` +
          `Pick a generator that does rather than emitting a type that quietly drops the constraint.`
      )
    }
    hashes[file] = createHash("sha256").update(raw).digest("hex").slice(0, 16)
    blocks.push(
      (await compile(JSON.parse(raw), basename(file, ".schema.json"), {
        bannerComment: "",
        additionalProperties: false,
        style: { semi: false, singleQuote: false, printWidth: 100 },
      })).trim()
    )
  }

  const manifest = JSON.stringify(hashes, null, 2).replace(/\n/g, "\n  ")
  const source =
    `${BANNER}\n` +
    `//\n` +
    `// Source: 434-context "05 System of Record/schemas" — canonical, and not in this\n` +
    `// repository. Regenerate with: tsx scripts/sor/generate-types.ts\n` +
    `\n` +
    blocks.join("\n\n") +
    `\n\n/** sha256[:16] of each source schema, for the drift check in the context repository. */\n` +
    `export const sorSchemaHashes = ${manifest} as const\n`

  if (process.argv.includes("--check")) {
    if (!existsSync(OUT)) throw new Error(`${OUT} does not exist; run without --check.`)
    const current = readFileSync(OUT, "utf8")
    if (current !== source) {
      throw new Error("lib/sor/types.generated.ts is stale or hand-edited. Regenerate it.")
    }
    console.log(`types.generated.ts matches ${files.length} schemas`)
    return
  }

  writeFileSync(OUT, source)
  writeFileSync(
    resolve("lib/sor/schemas.manifest.json"),
    JSON.stringify({ generated: new Date().toISOString().slice(0, 10), schemas: hashes, typesBody: bodyHash(source) }, null, 2) + "\n"
  )
  console.log(`wrote lib/sor/types.generated.ts from ${files.length} schema(s)`)
  for (const [f, h] of Object.entries(hashes)) console.log(`  ${f}  ${h}`)
}

main().catch((error) => {
  console.error(String(error instanceof Error ? error.message : error))
  process.exit(1)
})
