/**
 * CI check: `lib/sor/types.generated.ts` has not been hand-edited.
 *
 * This runs in the public repository, which does not hold the JSON Schemas —
 * they are canonical in the private context repo. So this cannot answer "are
 * the types current with the schemas"; that check belongs where the schemas
 * are, and reads `sorSchemaHashes` out of the generated file.
 *
 * What it can answer, with no access to anything else, is whether the committed
 * file still matches the hash recorded beside it when it was generated. That is
 * the failure this repository is exposed to: someone editing a generated file
 * by hand because it was faster than regenerating it.
 *
 * The same split already exists for the master: scripts/check_drift.py compares
 * artifacts against a document CI cannot see, so CI checks the rendered result
 * instead. See .github/workflows/verify-portfolio.yml.
 */
import { createHash } from "node:crypto"
import { readFileSync } from "node:fs"

const BANNER = "// Generated by scripts/sor/generate-types.ts. Do not edit."
const TYPES = "lib/sor/types.generated.ts"
const MANIFEST = "lib/sor/schemas.manifest.json"

const source = readFileSync(TYPES, "utf8")
const body = source.slice(source.indexOf("\n", source.indexOf(BANNER)) + 1)
const actual = createHash("sha256").update(body).digest("hex").slice(0, 16)
const { typesBody: expected, schemas } = JSON.parse(readFileSync(MANIFEST, "utf8"))

if (actual !== expected) {
  console.error(
    `${TYPES} does not match ${MANIFEST}.\n` +
      `  recorded ${expected}\n  actual   ${actual}\n` +
      `Regenerate rather than editing: tsx scripts/sor/generate-types.ts`
  )
  process.exit(1)
}

console.log(`${TYPES} matches its manifest (${actual}), ${Object.keys(schemas).length} schemas recorded`)
