// Generated by scripts/sor/generate-types.ts. Do not edit.
//
// Source: 434-context "05 System of Record/schemas" — canonical, and not in this
// repository. Regenerate with: tsx scripts/sor/generate-types.ts

export type Band = Band1 & {
  name: string
  revenue_usd?: Range
  employees?: Range
} & Band1 & {
    name: string
    revenue_usd?: Range
    employees?: Range
  }
export type Band1 =
  | {
      [k: string]: unknown
    }
  | {
      [k: string]: unknown
    }

/**
 * Master §5.6–5.10. Cohort rules live in the policy document, not here.
 */
export interface OutboundCohort {
  key: string
  letter: "A" | "B" | "C" | "D" | "E"
  name: string
  objective: string
  target_profile: string[]
  target_profile_notes?: string | null
  qualification_signals: string[]
  qualification_signal_notes?: string | null
  proof: {
    portfolio_record: string | null
    as_written: string
    /**
     * Where this proof comes from when it is not one named record. A cohort may cite a class of proof — a collection, or a query across one — and before this that was a string the extractor tried to guess a record key from, failing silently when it could not. `restriction` names a master rule that governs anything written from the rows it returns.
     */
    selector?: null | {
      collection: "portfolio_records" | "talent_relationships"
      where?: {
        [k: string]: string
      }
      restriction?: string | null
    }
    /**
     * True where the proof is deliberately not a record and never will be — founder biography, for instance. Stated rather than inferred: this used to be a string match on the word 'founder' in the extractor, which excused the one case that was right and would have excused the next one that was not.
     */
    non_record?: boolean
  }[]
  narrative?: string | null
  first_pitch: string
  first_pitch_kind?: string
  secondary_routes?: string[]
  revenue_floor?: {
    amount_minor: number
    currency: string
  } | null
  /**
   * Who signs the outbound email. The vocabulary is the approved outbound skill's (assets/draft-set-format.md: 'Signer: 434 | founder'), not the master's — the master describes who speaks, the skill names the field. Recorded as `434` rather than `brand` so the row and the skill read the same.
   */
  signer: "434" | "founder"
  source?: string
  updated_at?: string
  updated_by?: string
  /**
   * Structured match fields read by the prospecting matcher and the ICP rubric (next-434media lib/prospecting/cohort-match.ts) in place of the prose target profile, which stays for people and agents. A company matches the cohort when one of its industries is listed, or when its size falls in one of the cohort's bands. Revenue decides the band when known; otherwise employee count. When both are unknown the company is neither matched nor ruled out by size: it is marked for review.
   */
  match: {
    /**
     * Industry categories, in the controlled vocabulary of next-434media lib/prospecting/industry-tags.ts (ICP_INDUSTRIES). defense_aerospace and marketing_agency were added to that vocabulary on 2026-10-09 for cohorts A and E; advanced_manufacturing and military_veteran (military health, and veteran-employment and defense-workforce organizations) were added the same day for cohort A. The two lists are copies: change both together. An empty list means the cohort matches on size only. A company can match several cohorts; every match is carried. LIMIT: some prose items cannot be told apart by industry alone and have no category here. Cohort A's dual-use technology companies look like any software or hardware company by industry, so software is deliberately not in cohort A; they are found by research or by the rep, not by this field.
     */
    industries: (
      | "healthcare_life_sciences"
      | "sports_fitness_lifestyle"
      | "tech_saas"
      | "capital_vc"
      | "media_broadcast"
      | "education_workforce"
      | "nonprofit_mission"
      | "cpg_consumer"
      | "civic_econ_dev"
      | "defense_aerospace"
      | "marketing_agency"
      | "advanced_manufacturing"
      | "military_veteran"
    )[]
    /**
     * Size bands, where the cohort is defined by size; null where it is not. Sources for cohort D's bands (founder decision 2026-10-08): REVENUE — National Center for the Middle Market (Ohio State), 'NCMM InfoSheet', https://www.middlemarketcenter.org/Media/Documents/NCMM%20InfoSheet.pdf: the U.S. middle market is annual revenue of $10 million to $1 billion (read through a web search result on 2026-10-08; the direct URL returned 404 on 2026-10-09). EMPLOYEES — Gartner Glossary, 'Midsize Enterprise (MSE)', https://www.gartner.com/en/information-technology/glossary/midsize-enterprise-mse: '$50 million and $1 billion in annual revenues and/or 100 to 2500 employees' (read through a web search result on 2026-10-08; the page redirected to Gartner's IT landing page on 2026-10-09); 100–2,500 approved by the founder 2026-10-08. OTHER BANDS RECORDED: Capterra's glossary, 'Midsize Enterprise (MSE)', https://www.capterra.ca/glossary/900/midsize-enterprise-mse, gives 100–1,000 employees; an earlier Gartner passage gives 100–999 employees with revenue over $50 million and under $1 billion; the Federal Reserve uses $10–$250 million revenue (as reported by Grata, https://grata.com/resources/what-is-the-middle-market).
     */
    size: null | {
      /**
       * @minItems 1
       */
      bands: [Band, ...Band[]]
    }
  }
}
/**
 * A numeric range. gte/lte are inclusive bounds, gt/lt exclusive.
 */
export interface Range {
  gt?: number
  gte?: number
  lt?: number
  lte?: number
}

/**
 * A constraint on outbound for one cohort: a first-pitch constraint, an operating rule, a hard escalation, a founder review. These were generated and validated for weeks and loaded by nothing, so the systems doing outbound could not see them.
 */
export interface CohortRule {
  key: string
  cohort: "A" | "B" | "C" | "D" | "E"
  kind: string
  text: string
  source: string
  updated_at?: string | null
  updated_by?: string | null
}

/**
 * Contracted crew. Aligns to schema.org Person.
 */
export interface Contractor {
  key: string
  name: string
  email?: string | null
  roles: string[]
  standard_rates?: {
    unit: string
    amount: {
      amount_minor: number
      currency: string
    }
  }[]
  status: "active" | "inactive"
  notes?: string | null
  source?: string
  updated_at?: string
  updated_by?: string
}

/**
 * An open item from the Implementation Decisions Register whose status changes what an agent may do. The register holds the decision; this holds the state a job branches on.
 */
export interface LaunchDependency {
  key: string
  subject: string
  status: "open" | "closed"
  /**
   * What a job must do while this is open. Written so it can be followed without reading the register.
   */
  effect_while_open: string
  gating_ref: string
  register_status_as_written?: string
  closed_on?: string | null
  source: string
  updated_at?: string
  updated_by?: string
}

/**
 * Routable partner services (master §2.11).
 */
export interface PartnerService {
  key: string
  partner: string
  service: string
  tier: "core_2_11" | "snapshot" | "never_route"
  confirmed: boolean
  last_reviewed: string
  source?: string
  updated_at?: string
  updated_by?: string
}

/**
 * The policy and the voice files, served to jobs through the connector. The master remains the source; these are cut from it or synced from the voice system.
 */
export interface PolicyDocument {
  key: string
  kind: "policy" | "voice"
  title: string
  version: string
  body: string
  bytes?: number
  sha256?: string
  source: string
  updated_at?: string
  updated_by?: string
}

/**
 * Master §4.5 record standard. Aligns to schema.org CreativeWork. *_as_written fields preserve master text where structure is not yet decided.
 */
export interface PortfolioRecord {
  key: string
  title: string
  commercial_model: "Original IP" | "Platforms for Brands" | "Productions for Brands"
  parent_key?: string | null
  /**
   * @minItems 1
   */
  production_categories: [
    "Content" | "Experience" | "Platform" | "Digital Infrastructure",
    ...("Content" | "Experience" | "Platform" | "Digital Infrastructure")[]
  ]
  client_or_partner_as_written?: string | null
  role_434: string
  founder_credit?: null | {
    roles: string[] | null
    as_written: string
  }
  collaborator_credits_as_written?: string | null
  years?: null | {
    start: number
    end: number | null
    ongoing: boolean
  }
  years_as_written?: string | null
  /**
   * Prefer an operating_statuses term; literal alternatives allowed by §4.5.
   */
  operating_status: string
  work_page: {
    published: boolean
    reason: string | null
  }
  public_url?: string | null
  approved_public_description: string
  internal_context?: string | null
  proof_assets_as_written?: string | null
  video?: string | null
  /**
   * A departure from the Display and Design Standard approved for this record, with its factor, the rule departed from, who approved it and when, and the condition that ends it. lib/sor/work-records.ts reads it.
   */
  display_exception?: string | null
  rights_defaults?: null | {
    creator: string
    copyright_notice: string
    credit_line: string
    usage_terms: string
  }
  registered_identifier_as_written?: string | null
  restrictions_as_written?: string | null
  source?: string
  updated_at?: string
  updated_by?: string
}

/**
 * A price the founder set below cost-sheet rates or below a minimum. Pricing Architecture §5.3: approved by the act of setting it; its rationale is recorded, not reviewed; logged here and never in governing documents, so exceptions can be counted and reported on. Money follows contractor.standard_rates: integer minor units with an ISO 4217 code. agreed_price is a list because a quote can offer options; once a row is agreed, delivered or paid it holds exactly one, which validate.py checks. Internal, never quotable.
 */
export interface PricingException {
  key: string
  date: string
  client: string
  project: string
  scope?: string | null
  /**
   * The cost-sheet line or minimum the price falls below, with its amount.
   */
  list_basis: string
  /**
   * @minItems 1
   */
  agreed_price: [
    {
      label?: string | null
      amount_minor: number
    },
    ...{
      label?: string | null
      amount_minor: number
    }[]
  ]
  currency: string
  reason_category: "icp_visibility" | "relationship" | "strategic_ip" | "other"
  /**
   * One sentence.
   */
  reason: string
  series: boolean
  status: "quoted" | "agreed" | "delivered" | "paid" | "lost"
  approved_by: "founder"
  /**
   * Reserved for the CRM link.
   */
  deal_ref?: string | null
  source: string
  updated_at?: string | null
  updated_by?: string | null
}

/**
 * Master §6.1–6.2 numbers. Never quoted to a prospect.
 */
export interface QualificationThreshold {
  key: string
  applies_to:
    | "commercial-account"
    | "owned-ip-participation"
    | "client-platform"
    | "client-production"
    | "consult-first-strategy"
    | "distribution-referral"
    | "ampd-applicant"
  kind: "gate" | "rate" | "none" | "cut_line"
  amount: {
    amount_minor: number
    currency: string
  } | null
  unit: "total" | "total_committed" | "hour" | "annual_revenue" | "single_funding_round" | null
  annual_floor?: {
    amount_minor: number
    currency: string
  } | null
  quotable: boolean
  notes?: string
  source?: string
  updated_at?: string
  updated_by?: string
}

/**
 * From 434_Pricing_Architecture.md. Loaded by Claude Code from the repo document.
 */
export interface RateCardLine {
  key: string
  service: string
  layer: "fixed_minimum" | "public_anchor" | "internal_cost"
  unit: string
  amount: {
    amount_minor: number
    currency: string
  }
  cost_basis?: string | null
  modifiers?: {
    kind: "rush" | "pass_through_markup"
    value: number
  }[]
  provisional: boolean
  source?: string
  updated_at?: string
  updated_by?: string
}

/**
 * A recurring talent collaborator and the engagements they appeared in. Master 4.11 holds the rules: talent is credited within the production, a recurring relationship is not a standalone portfolio title, and this history must never be used to imply artist management, marketing representation, or exclusivity. That last rule is why these rows are internal.
 */
export interface TalentRelationship {
  key: string
  name: string
  relationship_type: string
  relevant_engagements_as_written: string
  source: string
  updated_at?: string | null
  updated_by?: string | null
}

/**
 * The order the Work page presents the three commercial models in. Model and position only: the label is a formatting of the two, and the definition stays canonical in master 4.3 and is generated into the website from there, so it is not duplicated here.
 */
export interface WorkPageSection {
  key: string
  model: string
  position: number
  source: string
  updated_at?: string | null
  updated_by?: string | null
}

/** sha256[:16] of each source schema, for the drift check in the context repository. */
export const sorSchemaHashes = {
    "cohort.schema.json": "e88419f1a6a6b0ba",
    "cohort_rule.schema.json": "6dba9c5ea2c43de8",
    "contractor.schema.json": "0e30b1e384417bfe",
    "launch_dependency.schema.json": "b60a01e2bf2af341",
    "partner_service.schema.json": "27d5fa1bf7ad7543",
    "policy_document.schema.json": "4e1d0184b8692961",
    "portfolio_record.schema.json": "299576a4a45c00dc",
    "pricing_exception.schema.json": "30bd46b76e2e2ded",
    "qualification_threshold.schema.json": "4b346713da931afd",
    "rate_card_line.schema.json": "099711957961ffe2",
    "talent_relationship.schema.json": "f0414d7b7a227ea1",
    "work_page_section.schema.json": "af3bd0fab24e4fe8"
  } as const
