// Generated by scripts/sor/generate-types.ts. Do not edit.
//
// Source: 434-context "05 System of Record/schemas" — canonical, and not in this
// repository. Regenerate with: tsx scripts/sor/generate-types.ts

/**
 * Master §5.6–5.10. Cohort rules live in the policy document, not here.
 */
export interface OutboundCohort {
  key: string
  letter: "A" | "B" | "C" | "D" | "E"
  name: string
  objective: string
  target_profile: string[]
  target_profile_notes?: string | null
  qualification_signals: string[]
  qualification_signal_notes?: string | null
  proof: {
    portfolio_record: string | null
    as_written: string
  }[]
  narrative?: string | null
  first_pitch: string
  first_pitch_kind?: string
  secondary_routes?: string[]
  revenue_floor?: {
    amount_minor: number
    currency: string
  } | null
  /**
   * Who signs the outbound email. The vocabulary is the approved outbound skill's (assets/draft-set-format.md: 'Signer: 434 | founder'), not the master's — the master describes who speaks, the skill names the field. Recorded as `434` rather than `brand` so the row and the skill read the same.
   */
  signer: "434" | "founder"
  source?: string
  updated_at?: string
  updated_by?: string
}

/**
 * Contracted crew. Aligns to schema.org Person.
 */
export interface Contractor {
  key: string
  name: string
  email?: string | null
  roles: string[]
  standard_rates?: {
    unit: string
    amount: {
      amount_minor: number
      currency: string
    }
  }[]
  status: "active" | "inactive"
  notes?: string | null
  source?: string
  updated_at?: string
  updated_by?: string
}

/**
 * An open item from the Implementation Decisions Register whose status changes what an agent may do. The register holds the decision; this holds the state a job branches on.
 */
export interface LaunchDependency {
  key: string
  subject: string
  status: "open" | "closed"
  /**
   * What a job must do while this is open. Written so it can be followed without reading the register.
   */
  effect_while_open: string
  gating_ref: string
  register_status_as_written?: string
  closed_on?: string | null
  source: string
  updated_at?: string
  updated_by?: string
}

/**
 * Routable partner services (master §2.11).
 */
export interface PartnerService {
  key: string
  partner: string
  service: string
  tier: "core_2_11" | "snapshot" | "never_route"
  confirmed: boolean
  last_reviewed: string
  source?: string
  updated_at?: string
  updated_by?: string
}

/**
 * The policy and the voice files, served to jobs through the connector. The master remains the source; these are cut from it or synced from the voice system.
 */
export interface PolicyDocument {
  key: string
  kind: "policy" | "voice"
  title: string
  version: string
  body: string
  bytes?: number
  sha256?: string
  source: string
  updated_at?: string
  updated_by?: string
}

/**
 * Master §4.5 record standard. Aligns to schema.org CreativeWork. *_as_written fields preserve master text where structure is not yet decided.
 */
export interface PortfolioRecord {
  key: string
  title: string
  commercial_model: "Original IP" | "Platforms for Brands" | "Productions for Brands"
  parent_key?: string | null
  /**
   * @minItems 1
   */
  production_categories: [
    "Content" | "Experience" | "Platform" | "Digital Infrastructure",
    ...("Content" | "Experience" | "Platform" | "Digital Infrastructure")[]
  ]
  client_or_partner_as_written?: string | null
  role_434: string
  founder_credit?: null | {
    roles: string[] | null
    as_written: string
  }
  collaborator_credits_as_written?: string | null
  years?: null | {
    start: number
    end: number | null
    ongoing: boolean
  }
  years_as_written?: string | null
  /**
   * Prefer an operating_statuses term; literal alternatives allowed by §4.5.
   */
  operating_status: string
  work_page: {
    published: boolean
    reason: string | null
  }
  public_url?: string | null
  approved_public_description: string
  internal_context?: string | null
  proof_assets_as_written?: string | null
  video?: string | null
  /**
   * A departure from the Display and Design Standard approved for this record, with its factor, the rule departed from, who approved it and when, and the condition that ends it. lib/sor/work-records.ts reads it.
   */
  display_exception?: string | null
  rights_defaults?: null | {
    creator: string
    copyright_notice: string
    credit_line: string
    usage_terms: string
  }
  registered_identifier_as_written?: string | null
  restrictions_as_written?: string | null
  source?: string
  updated_at?: string
  updated_by?: string
}

/**
 * Master §6.1–6.2 numbers. Never quoted to a prospect.
 */
export interface QualificationThreshold {
  key: string
  applies_to:
    | "commercial-account"
    | "owned-ip-participation"
    | "client-platform"
    | "client-production"
    | "consult-first-strategy"
    | "distribution-referral"
    | "ampd-applicant"
  kind: "gate" | "rate" | "none" | "cut_line"
  amount: {
    amount_minor: number
    currency: string
  } | null
  unit: "total" | "total_committed" | "hour" | "annual_revenue" | "single_funding_round" | null
  annual_floor?: {
    amount_minor: number
    currency: string
  } | null
  quotable: boolean
  notes?: string
  source?: string
  updated_at?: string
  updated_by?: string
}

/**
 * From 434_Pricing_Architecture.md. Loaded by Claude Code from the repo document.
 */
export interface RateCardLine {
  key: string
  service: string
  layer: "fixed_minimum" | "public_anchor" | "internal_cost"
  unit: string
  amount: {
    amount_minor: number
    currency: string
  }
  cost_basis?: string | null
  modifiers?: {
    kind: "rush" | "pass_through_markup"
    value: number
  }[]
  provisional: boolean
  source?: string
  updated_at?: string
  updated_by?: string
}

/**
 * A recurring talent collaborator and the engagements they appeared in. Master 4.11 holds the rules: talent is credited within the production, a recurring relationship is not a standalone portfolio title, and this history must never be used to imply artist management, marketing representation, or exclusivity. That last rule is why these rows are internal.
 */
export interface TalentRelationship {
  key: string
  name: string
  relationship_type: string
  relevant_engagements_as_written: string
  source: string
  updated_at?: string | null
  updated_by?: string | null
}

/**
 * The order the Work page presents the three commercial models in. Model and position only: the label is a formatting of the two, and the definition stays canonical in master 4.3 and is generated into the website from there, so it is not duplicated here.
 */
export interface WorkPageSection {
  key: string
  model: string
  position: number
  source: string
  updated_at?: string | null
  updated_by?: string | null
}

/** sha256[:16] of each source schema, for the drift check in the context repository. */
export const sorSchemaHashes = {
    "cohort.schema.json": "14255713087a8896",
    "contractor.schema.json": "0e30b1e384417bfe",
    "launch_dependency.schema.json": "b60a01e2bf2af341",
    "partner_service.schema.json": "27d5fa1bf7ad7543",
    "policy_document.schema.json": "4e1d0184b8692961",
    "portfolio_record.schema.json": "299576a4a45c00dc",
    "qualification_threshold.schema.json": "4b346713da931afd",
    "rate_card_line.schema.json": "099711957961ffe2",
    "talent_relationship.schema.json": "f0414d7b7a227ea1",
    "work_page_section.schema.json": "af3bd0fab24e4fe8"
  } as const
