/** Offline only. Run with tsx --test; all transport/persistence is injected. */
import { test } from "node:test"
import assert from "node:assert/strict"
import { draftBatch, manifestHash, dryRun, resetUnpublishedPreparation, assertOperatorSettlement, confirmStoppedRun, runOwnedMeta, guardedContentUpdate, type MetaManifest, type MetaRecord, type MetaStore, type MetaProvider, type MetaDestination } from "../owned-meta-publisher"
import { createMetaProvider, checkMetaCapability, type MetaPublishingEvidence } from "../instagram-publishing"
import { assetDigest, approvedObject, uploadApprovedAsset, readTrustedAsset, measureExport } from "../owned-meta-upload"

const png=Buffer.from([137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,4,56,0,0,5,70])
function manifest(format:MetaManifest["format"]="still",ai=false):MetaManifest {
  const asset={name:"test.png",sha256:assetDigest(png),size:png.length,mime:"image/png" as const,width:1080,height:1350,provenance:{source:"test",templateRevision:"v1",generator:"none",metadata:"unverified" as const}}
  return {schema:1,revision:1,brand:"milcity",format,assets:format==="carousel"?[asset,{...asset,name:"second.png"}]:format==="video"?[{...asset,mime:"video/mp4",duration:5}]:[asset],captions:{instagram:"IG exact",facebook:"FB exact"},destinations:{appId:"1",pageId:"2",instagramId:"3",apiVersion:"v23.0"},placements:{instagram:format==="video"?"reels":"feed",facebook:format==="video"?"reels":"feed"},instagramShareToFeed:false,aiGenerated:ai,publicHostingApproved:true}
}
function record(m=manifest()):MetaRecord {const batch=draftBatch("batch-1",m);batch.approval={by:"reviewer@example.test",at:"2026-10-09T00:00:00Z",hash:batch.hash};return{archived:false,revision:1,batch}}
class Store implements MetaStore {
  value:MetaRecord; version=0; conflicts=0; events:unknown[]=[]
  constructor(r=record()){this.value=structuredClone(r)}
  async read(){return structuredClone(this.value)}
  async update<T>(_id:string,fn:(r:MetaRecord)=>{next?:MetaRecord;result:T}):Promise<T>{for(;;){const version=this.version,{next,result}=fn(structuredClone(this.value));await new Promise(r=>setImmediate(r));if(version!==this.version){this.conflicts++;continue}if(next){this.value=next;this.version++}return result}}
  async event(...args:unknown[]){this.events.push(args)}
}
function fakeProvider(options:{failFinal?:MetaDestination;notReady?:MetaDestination}={}):MetaProvider&{calls:string[]} {const calls:string[]=[];return {calls,preflight:()=>null,prepare:async(_m,d,_u,p,save)=>{calls.push(`prepare:${d}`);await save("container",d==="instagram"?"11":"22");return{ready:options.notReady!==d,preparation:{...p,container:d==="instagram"?"11":"22"}}},publish:async(_m,d)=>{calls.push(`publish:${d}`);if(d===options.failFinal)throw new Error("lost response");return d==="instagram"?"101":"202"},verify:async(_m,d)=>({verified:true,permalink:`https://www.${d}.com/p/verified`})}}
const run=(store:Store,provider:MetaProvider,runId="r",enabled=true)=>runOwnedMeta({id:"p",runId,store,provider,enabled:async()=>enabled,upload:async b=>b.manifest.assets.map(a=>approvedObject(b,a).url),now:()=>"2026-10-09T00:00:00Z"})
function evidence(m:MetaManifest):MetaPublishingEvidence{return{verifiedAt:"2026-10-09T00:00:00Z",credentialKind:"system_user_page",...m.destinations,formats:Object.fromEntries(["instagram:still:feed","facebook:still:feed","instagram:carousel:feed","facebook:carousel:feed","instagram:video:reels","facebook:video:reels","facebook:video:video"].map(k=>[k,{mimeTypes:["image/png","image/jpeg","video/mp4"],maxBytes:100000,maxItems:20,minAspect:0.1,maxAspect:10,maxDuration:100,aiLabel:true}])),facebookReelAiPhase:"finish"}}

test("disabled and pure dry-run perform zero external effects",async()=>{const s=new Store(),p=fakeProvider();assert.equal(dryRun(s.value).hash,s.value.batch.hash);await assert.rejects(run(s,p,"r",false),/disabled/);assert.deepEqual(p.calls,[]);assert.equal(s.version,0)})
test("hash binds both captions, account, item order, AI flag and feed-sharing option",()=>{const m=manifest("carousel"),h=manifestHash(m);for(const change of [(x:MetaManifest)=>x.captions.facebook="changed",(x:MetaManifest)=>x.destinations.pageId="99",(x:MetaManifest)=>x.assets.reverse(),(x:MetaManifest)=>x.aiGenerated=true,(x:MetaManifest)=>x.instagramShareToFeed=true]){const x=structuredClone(m);change(x);assert.notEqual(manifestHash(x),h)}})
test("legacy status or changed approval cannot qualify",()=>{const r=record();delete r.batch.approval;assert.throws(()=>dryRun(r),/approval/);const edited=record();edited.batch.manifest.captions.instagram="new";assert.throws(()=>dryRun(edited),/approval/)})
test("one transaction claim defeats simultaneous clicks",async()=>{const s=new Store(),p=fakeProvider();const result=await Promise.allSettled([run(s,p,"a"),run(s,p,"b")]);assert.equal(result.filter(x=>x.status==="rejected").length,1);assert.equal(p.calls.filter(x=>x==="publish:instagram").length,1);assert.equal(p.calls.filter(x=>x==="publish:facebook").length,1);assert.ok(s.conflicts>0)})
test("unknown final outcome never resends; successful other destination remains untouched",async()=>{const s=new Store(),p=fakeProvider({failFinal:"instagram"});await run(s,p);await run(s,p,"again");assert.equal(p.calls.filter(x=>x==="publish:instagram").length,1);assert.equal(p.calls.filter(x=>x==="publish:facebook").length,1);assert.equal(s.value.batch.jobs.instagram.status,"needs_reconciliation");assert.equal(s.value.batch.jobs.facebook.status,"verified")})
test("processing is explicitly resumed; known container is checkpointed",async()=>{const s=new Store(),p=fakeProvider({notReady:"instagram"});await run(s,p);assert.equal(s.value.batch.jobs.instagram.preparation.container,"11");assert.equal(s.value.batch.jobs.instagram.status,"processing");assert.equal(s.value.batch.claim,null);assert.ok(!p.calls.includes("publish:instagram"))})
test("archive between preparation and final dispatch prevents publication",async()=>{const s=new Store(),p=fakeProvider();const original=p.prepare;p.prepare=async(...args)=>{const r=await original(...args);s.value.archived=true;return r};await assert.rejects(run(s,p));assert.ok(!p.calls.some(x=>x.startsWith("publish:")));assert.equal(s.value.batch.approval?.by,"reviewer@example.test")})
test("generic writer cannot forge fields; relevant edits invalidate and started work freezes",()=>{assert.throws(()=>guardedContentUpdate({}, {owned_meta:{}}),/server-owned/);assert.deepEqual(guardedContentUpdate({owned_meta:{started:false},owned_meta_revision:1,social_copy:"a"},{social_copy:"b"}),{social_copy:"b",owned_meta_revision:2,owned_meta:null,status:"needs_approval"});assert.throws(()=>guardedContentUpdate({owned_meta:{started:true},assets:[]},{assets:[{}]}),/frozen/);assert.deepEqual(guardedContentUpdate({owned_meta:{started:true}},{comments:[]}),{comments:[]})})
test("all six platform/format capabilities remain represented; AI FB photo alone holds",()=>{for(const format of ["still","carousel","video"] as const){const m=manifest(format);for(const d of ["instagram","facebook"] as const)assert.equal(checkMetaCapability(m,d,evidence(m)),null)}const m=manifest("still",true);assert.equal(checkMetaCapability(m,"instagram",evidence(m)),null);assert.match(checkMetaCapability(m,"facebook",evidence(m))!,/manual/);const wrong=evidence(m);wrong.pageId="4";assert.match(checkMetaCapability(m,"instagram",wrong)!,/verification/)})
test("unverified format limits fail closed",()=>{const m=manifest();const e=evidence(m);delete e.formats["instagram:still:feed"];assert.match(checkMetaCapability(m,"instagram",e)!,/verified limits/)})
test("create-only 412 recovery reuses exactly matching public bytes",async()=>{const b=record().batch;let upload=0;const fetcher=(async(url:URL|string,init?:RequestInit)=>{if(String(url).includes('/upload/')){upload++;assert.equal(new URL(String(url)).searchParams.get("ifGenerationMatch"),"0");assert.equal(init?.method,"POST");return new Response("",{status:412})}return new Response(png)}) as typeof fetch;assert.equal(await uploadApprovedAsset({batch:b,asset:b.manifest.assets[0],bytes:png,accessToken:async()=>"fake",fetcher}),approvedObject(b,b.manifest.assets[0]).url);assert.equal(upload,1)})
test("wrong public bytes, untrusted origins and redirects cannot be uploaded/reused",async()=>{const b=record().batch;await assert.rejects(uploadApprovedAsset({batch:b,asset:b.manifest.assets[0],bytes:png,accessToken:async()=>"fake",fetcher:(async(url)=>String(url).includes('/upload/')?new Response("",{status:412}):new Response("wrong")) as typeof fetch}),/changed/);let calls=0;await assert.rejects(readTrustedAsset("http://127.0.0.1/private",[],(async()=>{calls++;return new Response()}) as typeof fetch),/approved HTTPS/);assert.equal(calls,0)})
test("actual PNG dimensions are measured from bytes",()=>{assert.deepEqual(measureExport(png),{mime:"image/png",width:1080,height:1350})})

test("IG carousel AI flag goes on parent only; non-AI omits it",async()=>{for(const ai of [false,true]){const m=manifest("carousel",ai),calls:{path:string;body:URLSearchParams}[]=[];let n=10;const provider=createMetaProvider({accessToken:"fake",evidence:evidence(m),beforeMutation:async()=>{},fetcher:(async(url,init)=>{if(init?.method==="POST"){calls.push({path:new URL(String(url)).pathname,body:new URLSearchParams(init.body as URLSearchParams)});return Response.json({id:String(n++)})}return Response.json({status_code:"FINISHED"})}) as typeof fetch});await provider.prepare(m,"instagram",["https://example.test/a","https://example.test/b"],{},async()=>{});assert.equal(calls.length,3);assert.equal(calls[0].body.has("is_ai_generated"),false);assert.equal(calls[1].body.has("is_ai_generated"),false);assert.equal(calls[2].body.get("is_ai_generated"),ai?"true":null)}})
test("FB still and multi-photo endpoints are final publishing; preparation is unpublished",async()=>{for(const format of ["still","carousel"] as const){const m=manifest(format),calls:{path:string;body:URLSearchParams}[]=[];let n=10;const provider=createMetaProvider({accessToken:"fake",evidence:evidence(m),beforeMutation:async()=>{},fetcher:(async(url,init)=>{calls.push({path:new URL(String(url)).pathname,body:new URLSearchParams(init?.body as URLSearchParams)});return Response.json({id:String(n++),post_id:"2_55"})}) as typeof fetch});const prepared=await provider.prepare(m,"facebook",m.assets.map(()=>"https://example.test/a"),{},async()=>{});assert.equal(calls.length,format==="still"?0:2);for(const call of calls)assert.equal(call.body.get("published"),"false");await provider.publish(m,"facebook",["https://example.test/a"],prepared.preparation);assert.ok(calls.at(-1)!.path.endsWith(format==="still"?"/photos":"/feed"));if(format==="still")assert.equal(calls.at(-1)!.body.get("published"),"true")}})
test("verification requires membership in exact account published collection",async()=>{const m=manifest();const provider=createMetaProvider({accessToken:"fake",evidence:evidence(m),beforeMutation:async()=>{throw Error("must not mutate")},fetcher:(async()=>Response.json({data:[]})) as typeof fetch});assert.equal((await provider.verify(m,"facebook","2_55")).verified,false)})

test("late preparation cannot dispatch after operator releases/reclaims its claim",async()=>{const s=new Store(),p=fakeProvider();const original=p.prepare;p.prepare=async(...args)=>{const out=await original(...args);s.value.batch.claim="replacement";return out};await assert.rejects(run(s,p),/Claim changed/);assert.ok(!p.calls.some(x=>x.startsWith("publish:")));assert.equal(s.value.batch.claim,"replacement")})
test("disable after preparation prevents final publication",async()=>{const s=new Store(),p=fakeProvider();let enabled=true;const original=p.prepare;p.prepare=async(...args)=>{const out=await original(...args);enabled=false;return out};await assert.rejects(runOwnedMeta({id:"p",runId:"r",store:s,provider:p,enabled:async()=>enabled,upload:async()=>["https://example.test/a"]}),/disabled/);assert.ok(!p.calls.some(x=>x.startsWith("publish:")))})
test("safe preparation failure on IG does not prevent Facebook progress",async()=>{const s=new Store(),p=fakeProvider();const original=p.prepare;p.prepare=async(...args)=>{if(args[1]==="instagram")throw Error("expired container");return original(...args)};await run(s,p);assert.equal(s.value.batch.jobs.instagram.status,"manual_required");assert.equal(s.value.batch.jobs.facebook.status,"verified")})
test("operator-confirmed manual job never publishes again",async()=>{const r=record();r.batch.jobs.facebook.status="operator_confirmed";r.batch.jobs.facebook.remoteId="2_77";const s=new Store(r),p=fakeProvider();await run(s,p);assert.ok(!p.calls.includes("publish:facebook"));assert.equal(s.value.batch.jobs.facebook.remoteId,"2_77")})
test("MP4 dimensions and duration are read from boxes rather than supplied values",()=>{const box=(kind:string,payload:Buffer)=>{const h=Buffer.alloc(8);h.writeUInt32BE(payload.length+8);h.write(kind,4);return Buffer.concat([h,payload])};const tkhd=Buffer.alloc(84);tkhd.writeInt32BE(65536,40);tkhd.writeInt32BE(65536,56);tkhd.writeUInt32BE(1080*65536,76);tkhd.writeUInt32BE(1920*65536,80);const hdlr=Buffer.alloc(12);hdlr.write("vide",8);const mdhd=Buffer.alloc(24);mdhd.writeUInt32BE(1000,12);mdhd.writeUInt32BE(5875,16);const mp4=Buffer.concat([box("ftyp",Buffer.from("isom0000")),box("moov",box("trak",Buffer.concat([box("tkhd",tkhd),box("mdia",Buffer.concat([box("hdlr",hdlr),box("mdhd",mdhd)]))])))]);assert.deepEqual(measureExport(mp4),{mime:"video/mp4",width:1080,height:1920,duration:5.875});assert.throws(()=>measureExport(mp4.subarray(0,30)),/MP4|metadata/)})
test("Facebook ordinary video final call preserves conditional AI label",async()=>{for(const ai of [false,true]){const m=manifest("video",ai);m.placements.facebook="video";let request:URLSearchParams|undefined;const p=createMetaProvider({accessToken:"fake",evidence:evidence(m),beforeMutation:async()=>{},fetcher:(async(_u,init)=>{request=new URLSearchParams(init?.body as URLSearchParams);return Response.json({id:"55"})}) as typeof fetch});await p.publish(m,"facebook",["https://example.test/video"],{});assert.equal(request?.get("is_ai_generated"),ai?"true":null);assert.equal(request?.get("published"),"true")}})


test("manual completion cannot be reset into a duplicate publish",async()=>{const r=record();r.batch.jobs.facebook={status:"operator_confirmed",preparation:{},remoteId:"2_88",manualEvidence:{by:"reviewer",at:"now",approvedHash:r.batch.hash,confirmation:"exact post"}};assert.throws(()=>resetUnpublishedPreparation(r,"facebook"),/completed/);const s=new Store(r),p=fakeProvider();await run(s,p);assert.ok(!p.calls.includes("publish:facebook"))})
test("operator settlement cannot clear an active run's claim",()=>{const r=record();r.batch.claim="active";assert.throws(()=>assertOperatorSettlement(r,r.batch.id),/active run/);assert.equal(r.batch.claim,"active")})


test("crashed final claim requires observed termination and preserves intent",()=>{const r=record();r.batch.claim="dead";r.batch.jobs.instagram.finalIntent={id:"dead:instagram",at:"then"};assert.throws(()=>confirmStoppedRun(r,"dead","reviewer","waiting","now"),/evidence/);confirmStoppedRun(r,"dead","reviewer","Runtime invocation confirmed terminated in run log","now");assert.equal(r.batch.claim,null);assert.equal(r.batch.jobs.instagram.finalIntent.id,"dead:instagram");assert.equal(r.batch.stoppedRuns?.[0].by,"reviewer")})
test("delayed old final response is retained but cannot dispatch another destination",async()=>{const s=new Store(),p=fakeProvider();const original=p.publish;p.publish=async(...args)=>{const id=await original(...args);await s.update("p",r=>{confirmStoppedRun(r,"r","reviewer","Observed request termination recorded by operator","now");return{next:r,result:null}});return id};await run(s,p);assert.equal(s.value.batch.jobs.instagram.remoteId,"101");assert.ok(!p.calls.includes("publish:facebook"));assert.ok(s.events.some(e=>JSON.stringify(e).includes("remote_final_observed")))})


test("auxiliary observation logging failure does not lose a known final ID",async()=>{const s=new Store(),p=fakeProvider();s.event=async(...args:unknown[])=>{if(JSON.stringify(args).includes("remote_final_observed"))throw Error("log unavailable")};await run(s,p);assert.equal(s.value.batch.jobs.instagram.remoteId,"101");assert.equal(s.value.batch.jobs.instagram.status,"verified");assert.equal(s.value.batch.jobs.facebook.remoteId,"202")})

test("actual preview handlers stop before authentication, storage and provider work",async()=>{
  const previous=process.env
  process.env={NODE_ENV:"test",VERCEL_ENV:"preview"}
  try {
    const route=await import("../../app/api/admin/crm/content-posts/[id]/owned-meta/route")
    const ctx={params:Promise.resolve({id:"offline-preview-test"})}
    const get=await route.GET(new Request("http://localhost/offline") as never,ctx)
    const post=await route.POST(new Request("http://localhost/offline",{method:"POST",body:'{"action":"execute"}'}) as never,ctx)
    assert.equal(get.status,200);assert.deepEqual(await get.json(),{enabled:false})
    assert.equal(post.status,423)
  } finally {process.env=previous}
})
